### ISSUE TITLE
Metadata initialization fails in SPDK (volatile = true)

### ISSUE THREAD

**Issue by Donaim** [Open-CAS/ocf#104]
Starting cache with configure option metadata_volatile = true fails with:
```
MalCache: Metadata Error
MalCache: Metadata Flush ERROR
MalCache: ERROR: Cannot save cache state
MalCache: Attaching cache device failed
```

Full log
```
Inserting cache MalCache
MalCache: Successfully added
MalCache: Cache mode : wb
MalCache: Super block config offset : 0 kiB
MalCache: Super block config size : 3544 B
MalCache: Super block runtime offset : 0 kiB
MalCache: Super block runtime size : 1512 B
MalCache: Reserved offset : 0 kiB
MalCache: Reserved size : 128 kiB
MalCache: Core config offset : 0 kiB
MalCache: Core config size : 360 kiB
MalCache: Core runtime offset : 0 kiB
MalCache: Core runtime size : 1172 kiB
MalCache: Core UUID offset : 0 kiB
MalCache: Core UUID size : 16384 kiB
MalCache: Cleaning offset : 0 kiB
MalCache: Cleaning size : 604 kiB
MalCache: Eviction offset : 0 kiB
MalCache: Eviction size : 400 kiB
MalCache: Collision offset : 0 kiB
MalCache: Collision size : 604 kiB
MalCache: List info offset : 0 kiB
MalCache: List info size : 856 kiB
MalCache: Hash offset : 0 kiB
MalCache: Hash size : 68 kiB
MalCache: Cache line size: 4 kiB
MalCache: Metadata capacity: 36 MiB
MalCache: OCF metadata self-test PASSED
MalCache: Metadata Error
MalCache: Metadata Flush ERROR
MalCache: ERROR: Cannot save cache state
MalCache: Attaching cache device failed
vbdev_ocf.c: 767:start_cache_cmpl: *ERROR*: Failed to attach cache device: -1000017
MalCache: Metadata Error
MalCache: Adding core core1 failed
vbdev_ocf.c: 906:add_core_cmpl: *ERROR*: Failed to add core device to cache instance
```

Messages printed during `ocf_metadata_hash_load_superblock` operation
pipeline->error gets set in `ocf_metadata_hash_generic_complete` to  -95
Backtrace:
```
(gdb) bt
#0  ocf_pipeline_finish (pipeline=0x200027c0b780, error=-95) at src/ocf/utils/utils_pipeline.c:123
#1  0x00005555555e9c37 in ocf_metadata_hash_generic_complete (priv=0x200027c0b7a8, error=-95) at src/ocf/metadata/metadata_hash.c:892
#2  0x00005555555f25d0 in raw_volatile_flush_all (cache=0x2000142273c0, raw=0x20001c2002d8, cmpl=0x5555555e9c05 <ocf_metadata_hash_generic_complete>, priv=0x200027c0b7a8) at src/ocf/metadata/metadata_raw_volatile.c:45
#3  0x00005555555e81e7 in ocf_metadata_raw_flush_all (cache=0x2000142273c0, raw=0x20001c2002d8, cmpl=0x5555555e9c05 <ocf_metadata_hash_generic_complete>, priv=0x200027c0b7a8) at src/ocf/metadata/metadata_raw.h:293
#4  0x00005555555ea5b2 in ocf_medatata_hash_flush_segment (pipeline=0x200027c0b780, priv=0x200027c0b7a8, arg=0x55555594b620 <ocf_metadata_hash_flush_sb_flush_segment_args>) at src/ocf/metadata/metadata_hash.c:1161
#5  0x00005555555f8227 in _ocf_pipeline_run_step (req=0x200014627f00) at src/ocf/utils/utils_pipeline.c:44
#6  0x00005555555e2c7f in ocf_io_handle (io=0x0, opaque=0x200014627f00) at src/ocf/ocf_queue.c:74
#7  0x00005555555e2d7d in ocf_queue_run_single (q=0x20001c2001c0) at src/ocf/ocf_queue.c:94
#8  0x00005555555b84a8 in mngt_queue_poll (opaque=0x20001c2001c0) at vbdev_ocf.c:796
#9  0x0000555555657520 in spdk_thread_poll (thread=0x555555dc2800, max_msgs=0, now=6263853433141732) at thread.c:456
#10 0x0000555555614b56 in _spdk_reactor_run (arg=0x555555dc25c0) at reactor.c:244
#11 0x0000555555614e78 in spdk_reactors_start () at reactor.c:333
#12 0x00005555556136fb in spdk_app_start (opts=0x7fffffffe270, start_fn=0x555555564450 <spdk_startup>, arg1=0x0) at app.c:677
#13 0x00005555555645e5 in main (argc=3, argv=0x7fffffffe408) at iscsi_tgt.c:112
```

Tested on d88a4ac57a9107f5fc764dc33426354dafe70165 and previus,
the issue reproduces precisely after 6cd84476f6825ebea64508c271210c0145e67881

SPDK version (devel): https://review.gerrithub.io/c/spdk/spdk/+/448537/9 

Bottom devices are RAM regions (malloc bdevs)

**Comment by imjfckm** [comment]
Thanks for your report. Apparently, while making metadata operations asynchronous we didn't preserve the old behavior for flushing volatile metadata raws.

Please test again with #105 I don't have any SPDK setups available for testing, sorry.

**Comment by Donaim** [comment]
@imjfckm Yes, it works, thank for quick responce and fix :)
