### ISSUE TITLE
Segmentation fault during send IO after initialization

### ISSUE THREAD

**Issue by Donaim** [Open-CAS/ocf#106]
I am getting NULL in `io->volume->cache` during `ocf_core_validate_io()` when sending reads immediately after initialization (in callback of `ocf_mngt_cache_add_core_finish()`)

Full backtrace:
```
(gdb) bt
#0  0x00005555555e1d95 in ocf_core_validate_io (io=0x200027228190) at src/ocf/ocf_core.c:202
#1  0x00005555555e1ec6 in ocf_core_submit_io_mode (io=0x200027228190, cache_mode=ocf_cache_mode_none) at src/ocf/ocf_core.c:233
#2  0x00005555555e2515 in ocf_core_volume_submit_io (io=0x200027228190) at src/ocf/ocf_core.c:395
#3  0x00005555555e0a5d in ocf_volume_submit_io (io=0x200027228190) at src/ocf/ocf_volume.c:237
#4  0x00005555555b701b in ocf_core_submit_io (io=0x200027228190) at /home/vmysak/samba_share0/cas/hyb/lib/bdev/ocf/env/include/ocf/ocf_core.h:156
#5  0x00005555555b7e7c in io_submit_to_ocf (bdev_io=0x200007043c00, io=0x200027228190) at vbdev_ocf.c:576
#6  0x00005555555b8026 in io_handle (ch=0x555555dc6cd0, bdev_io=0x200007043c00) at vbdev_ocf.c:625
#7  0x00005555555b80ba in vbdev_ocf_get_buf_cb (ch=0x555555dc6cd0, bdev_io=0x200007043c00, success=true) at vbdev_ocf.c:653
#8  0x0000555555621c36 in spdk_bdev_io_get_buf (bdev_io=0x200007043c00, cb=0x5555555b8074 <vbdev_ocf_get_buf_cb>, len=32768) at bdev.c:596
#9  0x00005555555b8116 in vbdev_ocf_submit_request (ch=0x555555dc6cd0, bdev_io=0x200007043c00) at vbdev_ocf.c:664
#10 0x00005555556242e3 in _spdk_bdev_io_submit (ctx=0x200007043c00) at bdev.c:1693
#11 0x000055555562462e in spdk_bdev_io_submit (bdev_io=0x200007043c00) at bdev.c:1741
#12 0x000055555562646b in spdk_bdev_read_blocks (desc=0x555555dc6bc0, ch=0x555555dc6c00, buf=0x200027002b80, offset_blocks=0, num_blocks=64, cb=0x5555555ae364 <spdk_gpt_bdev_complete>, cb_arg=0x555555dc6af0) at bdev.c:2595
#13 0x0000555555626326 in spdk_bdev_read (desc=0x555555dc6bc0, ch=0x555555dc6c00, buf=0x200027002b80, offset=0, nbytes=32768, cb=0x5555555ae364 <spdk_gpt_bdev_complete>, cb_arg=0x555555dc6af0) at bdev.c:2563
#14 0x00005555555ae699 in vbdev_gpt_read_gpt (bdev=0x555555dc3ea0) at vbdev_gpt.c:477
#15 0x00005555555ae810 in vbdev_gpt_examine (bdev=0x555555dc3ea0) at vbdev_gpt.c:528
#16 0x0000555555629192 in spdk_bdev_start (bdev=0x555555dc3ea0) at bdev.c:3740
#17 0x00005555556291d7 in spdk_bdev_register (bdev=0x555555dc3ea0) at bdev.c:3751
#18 0x00005555555b8ce9 in register_ocf_bdev (vbdev=0x555555dc3d20) at vbdev_ocf.c:1051
#19 0x00005555555b6e94 in vbdev_ocf_mngt_continue (vbdev=0x555555dc3d20, status=0) at utils.c:128
#20 0x00005555555b8905 in add_core_cmpl (cache=0x2000142273c0, core=0x200014227b80, priv=0x555555dc3d20, error=0) at vbdev_ocf.c:913
#21 0x00005555555d7e26 in ocf_mngt_cache_add_core_finish (pipeline=0x20000fc1fa00, priv=0x20000fc1fa28, error=0) at src/ocf/mngt/ocf_mngt_core.c:525
#22 0x00005555555f8512 in _ocf_pipeline_run_step (req=0x200014628180) at src/ocf/utils/utils_pipeline.c:47
#23 0x00005555555e2f3d in ocf_io_handle (io=0x0, opaque=0x200014628180) at src/ocf/ocf_queue.c:74
#24 0x00005555555e303b in ocf_queue_run_single (q=0x20001c2001c0) at src/ocf/ocf_queue.c:94
#25 0x00005555555b84a8 in mngt_queue_poll (opaque=0x20001c2001c0) at vbdev_ocf.c:796
#26 0x0000555555657b9e in spdk_thread_poll (thread=0x555555dc2800, max_msgs=0, now=6274227700624692) at thread.c:456
#27 0x00005555556151d4 in _spdk_reactor_run (arg=0x555555dc25c0) at reactor.c:244
#28 0x00005555556154f6 in spdk_reactors_start () at reactor.c:333
#29 0x0000555555613d79 in spdk_app_start (opts=0x7fffffffe270, start_fn=0x555555564450 <spdk_startup>, arg1=0x0) at app.c:677
#30 0x00005555555645e5 in main (argc=3, argv=0x7fffffffe408) at iscsi_tgt.c:112
```

Possible cause:
Address of io->volume in `ocf_core_validate_io()` is greater by 1 byte than address of core->volume in `ocf_mngt_cache_add_core_finish()`

Also, removing check at #202 in `ocf_core_validate_io()` silenced this error and everything worked OK

**Comment by imjfckm** [comment]
#107 should take care of that :) Thanks for the report!

**Comment by Donaim** [comment]
@imjfckm it does :) Thank you!

**Comment by Donaim** [comment]
@imjfckm it does :) Thank you!
